<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s 和你';
$Definition['%s comment'] = '%s 评论';
$Definition['%s comments'] = '%s 评论';
$Definition['%s Connect'] = '%s 连接';
$Definition['%s message'] = '%s 消息';
$Definition['%s New'] = '%s 新';
$Definition['%s new'] = '%s 新';
$Definition['%s New Plural'] = '%s 新';

$Definition['1 message'] = '1 消息';

$Definition['About'] = '关于';
$Definition['Accepted'] = '接受';
$Definition['Activity'] = '最新动态';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s 更新了 %6$s 个人资料.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s 更新了 %6$s 个人资料.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s 评论了 %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s added you to a %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s added  you to a %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s 评论了你的 %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s 评论了你的 %8$s.';
$Definition['Activity.Comment'] = '评论';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s 在 %8$s 中提到了 %3$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s 在 %8$s 中提到了 %3$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s 给 %3$s 发送了一个 %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s 给 %3$s 发送了一个 %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s 评论了 %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s 评论了 %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s 在 %8$s 提到了 %3$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s 在 %8$s 提到  %3$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s 导入了数据.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s 导入了数据.';
$Definition['Activity.Join.FullHeadline'] = '%1$s 加入.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s 加入.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s 接受了 %4$s 成员申请.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s 接受了 %4$s 成员申请.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s 为 %1$s 创建了账户.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s 为 %1$s 创建了账户.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s 接受了 %4$s 的注册邀请.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s 接受了 %4$s 的注册邀请.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s 发起了一个 %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s 发起了一个 %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s 修改了 %6$s 资料.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s 修改了 %6$s 个人头像.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s 修改了 %4$s 权限.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s 修改了 %4$s 权限.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s 登陆了.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s 登陆了.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s 在 %4$s %5$s 发表了内容.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s 写道:';
$Definition['Add'] = '添加';
$Definition['Add Comment'] = '添加评论';
$Definition['Add Info &amp; Create Account'] = '添加信息 &amp; 创建账号';
$Definition['Add Message'] = '添加消息';
$Definition['Add People to this Conversation'] = '邀请其他人参与会话';
$Definition['All Conversations'] = '所有会话';
$Definition['All Discussions'] = '所有讨论';
$Definition['Allow other members to see your email?'] = '其他成员是否可以看到你的 email 地址';
$Definition['Announce'] = '公告';
$Definition['Applicants'] = '申请人';
$Definition['Apply'] = '应用';
$Definition['Apply for Membership'] = '申请加入';
$Definition['Are you sure you want to do that?'] = '你确定你要这么做?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = '返回讨论';
$Definition['Bookmark'] = '收藏';
$Definition['bookmarked discussion'] = '收藏的讨论';
$Definition['Bookmarked Discussions'] = '收藏的讨论';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = '请确保你拥有所上传的文件的版权, 以及图片不违反本站的服务条款.';

$Definition['Cancel'] = '取消';
$Definition['Categories'] = '分类';
$Definition['Category'] = '分类';
$Definition['Change My Password'] = '修改我的密码';
$Definition['Change My Picture'] = '修改我的头像';
$Definition['Close'] = '关闭';
$Definition['comment'] = '评论';
$Definition['Comment'] = '评论';
$Definition['Confirm'] = '确认';
$Definition['Confirm Password'] = '确认密码';
$Definition['Connect'] = '连接';
$Definition['conversation'] = '会话';
$Definition['Conversations'] = '会话';
$Definition['Create One.'] = '创建一个.';

$Definition['Dashboard'] = '控制台';
$Definition['Date.DefaultDayFormat'] = '%b %e 日';
$Definition['Date.DefaultFormat'] = '%Y %b %e日';
$Definition['Date.DefaultTimeFormat'] = '%H:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = '删除';
$Definition['Delete Account'] = '删除帐号';
$Definition['Delete Conversation'] = '删除会话';
$Definition['Delete Discussion'] = '删除讨论';
$Definition['discussion'] = '讨论';
$Definition['Discussion Title'] = '讨论主题';
$Definition['Discussions'] = '讨论';
$Definition['Don\'t have an account? %s'] = '没有账号么? %s';
$Definition['dot'] = 'dot';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = '拖动并缩放下面的方块, 确定头像图标.';

$Definition['Edit'] = '编辑';
$Definition['Edit Account'] = '编辑账号';
$Definition['Edit My Account'] = '编辑我的账号';
$Definition['Edit My Thumbnail'] = '编辑我的头像';
$Definition['Edit Preferences'] = '编辑偏好设置';
$Definition['Email'] = 'Email';
$Definition['Email Notifications'] = 'Email 通知';
$Definition['Email Unavailable'] = 'Email 不可用';
$Definition['EmailInvitation'] = '你好!

	%1$s 邀请你加入 %2$s. 欢迎点击下面的链接加入:

	  %3$s

	  祝你开心每一天!';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

	You have been approved for membership. Sign in now at the following link:

	  %2$s
	    
	  Have a great day!';
$Definition['EmailNotification'] = '%1$s

	Follow the link below to check it out:
	%2$s

	Have a great day!';
$Definition['EmailPassword'] = 'Hello %1$s,

	%2$s has reset your password at %3$s. Your login credentials are now:

	  Email: %6$s
	    Password: %5$s
	      Url: %4$s

	      Have a great day!';
$Definition['EmailStoryNotification'] = '%1$s

	%3$s

	---
	Follow the link below to check it out:
	%2$s

	Have a great day!';
$Definition['EmailWelcome'] = 'Hello %1$s,

	%2$s has created an account for you at %3$s. Your login credentials are:

	  Email: %6$s
	    Password: %5$s
	      Url: %4$s

	      Have a great day!';
$Definition['EmailWelcomeConnect'] = 'Hello {User.Name},

	You have successfully connected to {Title}. Here is your information:

	  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['EmailWelcomeRegister'] = 'Hello {User.Name},

	You have successfully registered for an account at {Title}. Here is your information:

	  Username: {User.Name}
  Email: {User.Email}

You can access the site at {/,url,domain}.

Have a great day!';
$Definition['Enter the email address of the person you would like to invite:'] = '请输入你邀请对象的 email 地址:';
$Definition['Enter your Email address'] = '输入你的 Email 地址';
$Definition['Enter your existing account password.'] = '输入你的账号密码.';
$Definition['ErrorCredentials'] = '对不起, 你所输入的用户名或密码错误.';
$Definition['ErrorPermission'] = '对不起, 没有权限.';
$Definition['ErrorRecordNotFound'] = 'The requested record could not be found.';
$Definition['ErrorTermsOfService'] = '你必须同意服务条款.';

$Definition['Female'] = '女';
$Definition['Forgot?'] = '忘记了?';

$Definition['Gender'] = '性别';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Go';
$Definition['GuestModule.Message'] = '貌似这位同鞋你是新来的吧. 点下面的按钮可以加入我们!';

$Definition['he'] = '他';
$Definition['her'] = '她的';
$Definition['his'] = '他的';
$Definition['Howdy, Stranger!'] = '你好, 新同学!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = '我同意 <a id="TermsOfService" class="Popup" target="terms" href="%s">服务条款</a>';
$Definition['I remember now!'] = '我现在想起了!';
$Definition['In this Conversation'] = '在该会话';
$Definition['Inbox'] = '收件箱';
$Definition['Internal'] = '内部';
$Definition['Invitation Code'] = '邀请码';
$Definition['Invite'] = '邀请';
$Definition['Invited by'] = '邀请人';

$Definition['Joined'] = '加入';

$Definition['Keep me signed in'] = '记住我的登陆状态';

$Definition['Last Active'] = '最近一次活动';
$Definition['Login with Facebook'] = '使用 Facebook 登陆';

$Definition['Male'] = '男';
$Definition['Most recent by %1$s'] = '最近更新 %1$s';
$Definition['My Bookmarks'] = '我的收藏';
$Definition['My Discussions'] = '我的讨论';
$Definition['My Drafts'] = '我的草稿';
$Definition['My Invitations'] = '我的邀请';
$Definition['My Preferences'] = '我的偏好设置';

$Definition['Name Unavailable'] = '名字不可用';
$Definition['No discussions were found.'] = '木有找到讨论.';
$Definition['Notifications'] = '通知';
$Definition['Notify me of private messages.'] = '有新私人消息时通知我.';
$Definition['Notify me when I am added to private conversations.'] = '当我被加入到私人会话中时通知我.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = '当有人在我收藏的讨论中评论时通知我.';
$Definition['Notify me when people comment on my discussions.'] = '当有人在我的讨论中评论时通知我.';
$Definition['Notify me when people mention me in comments.'] = '当有人在评论中提到我时通知我.';
$Definition['Notify me when people mention me in discussion titles.'] = '当有人在讨论标题中提到我时通知我.';
$Definition['Notify me when people reply to my wall comments.'] = '当有人回复了我的评论时通知我.';
$Definition['Notify me when people write on my wall.'] = '当有人给我留言时通知我.';

$Definition['Okay'] = '确定';
$Definition['On'] = 'On';
$Definition['Options'] = '选项';
$Definition['Or you can...'] = '或者你可以...';
$Definition['Original'] = '原始图片';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = '密码';
$Definition['PasswordRequest'] = '你好 %1$s,

	Someone has requested to reset your password at %2$s. To reset your password, follow this link:

	  %3$s

	  If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = '密码不匹配';
$Definition['Permalink'] = '永久链接';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.';
$Definition['Post Comment'] = '发表评论';
$Definition['Post Discussion'] = '发表讨论';
$Definition['Powered by Vanilla'] = '动力源自 Vanilla';
$Definition['Preview'] = '预览';
$Definition['Profile Picture'] = '个人头像';

$Definition['Recent Activity'] = '最近活动';
$Definition['Recipients'] = '收件人';
$Definition['Redirecting...'] = '重定向...';
$Definition['Remember me on this computer'] = '在这台电脑上记住我';
$Definition['Remove My Picture'] = '删除我的头像';
$Definition['Request a new password'] = '请求新密码';
$Definition['Roles'] = '角色';

$Definition['Save'] = '保存';
$Definition['Save Draft'] = '保存草稿';
$Definition['Save Preferences'] = '保存偏好设置';
$Definition['Search'] = '搜索';
$Definition['Select an image on your computer (2mb max)'] = '从电脑中选择一张图片(最大 2mb)';
$Definition['Send %s a Message'] = '给 %s 发送消息';
$Definition['Send Message'] = '发送消息';
$Definition['Sent To'] = '发送给';
$Definition['Share'] = '分享';
$Definition['she'] = '她';
$Definition['Sign In'] = '登陆';
$Definition['Sign In with Google'] = 'Sign In with Google';
$Definition['Sign In with OpenID'] = 'Sign In with OpenID';
$Definition['Sign In with Twitter'] = 'Sign In with Twitter';
$Definition['Sign Out'] = '登出';
$Definition['Sign Up'] = '注册';
$Definition['Sink'] = '下沉';
$Definition['somebody'] = '某人';
$Definition['Start a New Conversation'] = '开始新会话';
$Definition['Start a New Discussion'] = '开始新讨论';
$Definition['Start Conversation'] = '开始会话';
$Definition['Started by %1$s'] = '发起人 %1$s';
$Definition['Status'] = '状态';

$Definition['Thank You!'] = '谢谢!';
$Definition['Thumbnail'] = '头像';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = '取消关注';
$Definition['Upload'] = '上传';
$Definition['Username'] = '用户名';

$Definition['ValidateBoolean'] = '%s is not a valid boolean.';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code>';
$Definition['ValidateDate'] = '%s is not a valid date.';
$Definition['ValidateDecimal'] = '%s is not a valid decimal.';
$Definition['ValidateEmail'] = '%s 格式错误.';
$Definition['ValidateEnum'] = '%s 无效.';
$Definition['ValidateInteger'] = '%s 不是有效的整数.';
$Definition['ValidateLength'] = '%1$s 内容太长, 超出限制 %2$s 字符.';
$Definition['ValidateMatch'] = '%s 字段不匹配.';
$Definition['ValidateMinimumAge'] = 'You must be at least 16 years old to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'You must select at least one %s.';
$Definition['ValidateRegex'] = '%s does not appear to be in the correct format.';
$Definition['ValidateRequired'] = '%s is required.';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s is not a valid time.';
$Definition['ValidateTimestamp'] = '%s is not a valid timestamp.';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = '访问';

$Definition['wall'] = 'wall';
$Definition['Why do you want to join?'] = '为什么你要加入呢?';
$Definition['Write a comment'] = '写评论';
$Definition['Write Comment'] = '新评论';
$Definition['Write something about yourself...'] = '写点关于你自己的东西吧...';

$Definition['you'] = '你';
$Definition['You'] = '你';
$Definition['You already have an account here.'] = '你在这里已经有账号了.';
$Definition['You are connected as %s through %s.'] = 'You are connected as %s through %s.';
$Definition['You do not have any conversations.'] = '你木有参与任何会话.';
$Definition['You do not have any notifications yet.'] = '你木有任何消息.';
$Definition['your'] = '你的';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Your application will be reviewed by an administrator. You will be notified by email if your application is approved.';
$Definition['Your registered username: <strong>%s</strong>'] = '你注册的用户名: <strong>%s</strong>';

/* from plugins */
// FileUpload
$Definition['Insert Image'] = '插入图片';
$Definition['Uploading...'] = '正在上传...';
$Definition['Attach a file'] = '添加文件';
$Definition['Attachments'] = '附件';

$Definition['In this Discussion'] = '本讨论参与人';

// WhosOnline
$Definition['Who\'s Online'] = '有谁在线上';
$Definition['Who\'s Online Settings'] = '在线列表设置';
$Definition['Rate of refresh'] = '刷新频率';
$Definition['Frequency'] = '刷新频率';
$Definition['In seconds'] = '秒';

// LastEdited
$Definition['Post edited by %1$s at %2$s'] = '在 %2$s 被 %1$s 最后编辑';

// PostCount
$Definition['Posts: %s'] = '发帖数: %s';
$Definition['Posts'] = '发帖数';

// 
$Definition['Quote'] = '引用';
$Definition['%s said:'] = '%s 说:';

// IP
$Definition['Last IP'] = '上次登陆IP';

// Following
$Definition['Friends'] = '好友';
$Definition['Followed by %d person'] = '有 %d 人关注';
$Definition['Followed by %d people'] = '有 %d 人关注';
$Definition['Following %d person'] = '关注 %s 人';
$Definition['Following %d people'] = '关注 %s 人';
$Definition['Stop following'] = '取消关注';
$Definition['Follow %s'] = '关注 %s';

// Voteing 部分汉化无法进行
$Definition['Votes'] = '投票';
$Definition['Vote'] = '投票';
$Definition['Follows'] = '关注';
$Definition['Views'] = '访问';
$Definition['Undo Follow'] = '取消关注';
$Definition['Follow'] = '关注';
$Definition['Popular'] = '最热';
$Definition['Date Added'] = '发表时间';
$Definition['sorted by'] = '排序依据';

// EasyReply
$Definition['Reply'] = '回复';

// MarkAllViewd
$Definition['Mark All Viewed'] = '标记所有为已读';

// Tagging
$Definition['Tags'] = '标签';
$Definition['Tagged'] = '标签';


// My hack code
$Definition['Email Or Username'] = '用户名或Email';

// from my found
$Definition['Change Picture'] = '更换图片';
$Definition['Edit Thumbnail'] = '编辑头像';
$Definition['Remove Picture'] = '删除图片';

$Definition['Save Comment'] = '保存评论';

$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s 被从 %2$s %3$s 移出, 并加入到 %4$s %5$s.';

$Definition['Unsink'] = '取消下沉';
$Definition['role'] = '角色';
$Definition['Clear'] = '清除';
$Definition['%s messages'] = '%s 消息';
$Definition['Add a Comment'] = '添加评论';
$Definition['message'] = '消息';
$Definition['Announcement'] = '公告';
$Definition['Unannounce'] = '取消公告';
$Definition['Old Password'] = '旧密码';
$Definition['Change Password'] = '修改密码';
$Definition['Closed'] = '已关闭';
$Definition['Reopen'] = '重新打开';
$Definition['Dismiss'] = '忽略公告';
$Definition['More Discussions'] = '更多讨论';
$Definition['You do not have any drafts.'] = '你木有任何草稿.';
$Definition['Edit Discussion'] = '编辑讨论';
$Definition['Comment by %s'] = '被 %s 评论';
$Definition['permalink'] = '永久链接';

$Definition['Your preferences have been saved.'] = '你的偏好设置已保存';

$Definition["↳ No results for '%s'"] = " '%s' 没有任何结果";
$Definition["↳ Search results for '%s'"] = "↳ '%s' 的搜索结果";

$Definition['More Results'] = '更多结果';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = '该图片为适合页面被自动缩小. 查看大图请点击.';
$Definition['Just you!'] = '只有你!';
$Definition['%s deleted this conversation.'] = '%s 删除了该会话';

$Definition['Body'] = '正文';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = '你已经在 %2$s 秒内发贴 %1$s 次, 为防止恶意灌水, 请等待 %3$s 秒后再重新发帖.';

$Definition['Draft saved at %s'] = '草稿在 %s 被保存';
$Definition['Username can only contain letters, numbers, underscores, and must be between 3 and 20 characters long.'] = '用户名不能包含非法字符. 长度不能少于3字符.';
$Definition['[%s] Invitation'] = '[%s] 邀请你加入';
$Definition['You have %s invitations left for this month.'] = '你本月还可以发送 %s 条邀请.';
$Definition['Your invitation has been sent.'] = '你的邀请已经发送';
$Definition['Uninvite'] = '取消邀请';
$Definition['Send Again'] = '重新发送';
$Definition['Pending'] = '等待接受';
$Definition['On'] = '时间';
$Definition['The invitation was removed successfully.'] = '邀请已经成功删除.';
$Definition['An invitation has already been sent to the email you entered.'] = '已经有其他用户的邀请发送给该地址.';
$Definition['The email you have entered is already related to an existing account.'] = '该邮件地址已经是网站的成员.';

