<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['Chinese'] = array (
  'Locale' => 'zh-CN',
  'Name' => 'Chinese Simple(简体中文)',
  'Description' => 'Chinese Simple(简体中文) ,modify by kanbox`s chinese locals file',
  'Version' => '20120415',
  'Author' => 'sarowlwp,Kanbox(first version)',
  'AuthorEmail' => 'sarowlwp@live.cn',
  'AuthorUrl' => 'http://weibo.com/sarowlwp',
  'License' => 'GPL2',
);


//////////////////////////////////
// Homepage
$Definition['Sign In'] = '登录';
$Definition['Apply for Membership'] = '注册会员!';
$Definition['Enter your Email address'] = '电子邮件';
$Definition['Enter your Email or Username'] = '电子邮件或用户名';
$Definition['Email or Username'] = '电子邮件或用户名';
$Definition['Request a new password →'] = '获取新密码 →';
$Definition['Sign In →'] = ' 登录 →';
$Definition['Forgot your password?'] = '忘记密码?';
$Definition['Apply for membership'] = '注册会员';
$Definition['Register for Membership'] = '会员注册';
$Definition['Registration is currently closed.'] = '注册通道目前关闭。';
$Definition['It looks like you\'re new here. If you want to get involved, click one of these buttons!'] = '新手上路，加入请点击其中一个按钮:';
$Definition['Invitation Code'] = '邀请码';
$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = '我同意 <a id="TermsOfService" class="Popup" target="terms" href="%s">服务条款</a>。';
$Definition['Terms of Service'] = '服务条款'; // manuell termsofservice.php bearbeitet; Rest noch offen; besser in definitions.php auslagern
$Definition['ErrorBadInvitationCode'] = '邀请码错误';
$Definition['Name Unavailable'] = '名字无效';
$Definition['Username can only contain letters, numbers, and underscores.'] = '用户名只能包含文字，数字和下划线。';
$Definition['The name you entered is already in use by another member.'] = '名字已存在。';
$Definition['The email you entered in use by another member.'] = '电子邮件地址已存在。'; //doppelt - siehe unten
$Definition['The reCAPTCHA value was not entered correctly. Please try again.'] = 'reCAPTCHA 值输入错误，请重新输入。';

$Definition['Passwords don\'t match'] = '密码输入不一致';
$Definition['You must agree to the terms of service.'] = '必须同意服务条款';
$Definition['Sign Up →'] = '登录 →';

$Definition['Powered by %s'] = '技术支持%s';


////////////////////////////////////
// Search
$Definition['Search'] = '搜索';
$Definition['No results for \'%s\''] = '没有符合 \'%s\'的结果';
$Definition['Search results for \'%s\''] = '在结果中搜索 \'%s\'';
$Definition['Comment by %s'] = '%s添加评论';
$Definition['Go'] = '搜索';


////////////////////////////////////
// Activity
$Definition['Activity'] = '动态';
$Definition['Recent Activity'] = '近期动态';
$Definition['%1$s signed in.'] = '%1$s已登录。';
$Definition['%1$s joined.'] = '%1$s加入了爱青大，各位列队欢迎';
$Definition['%1$s accepted %4$s invitation for membership.'] = '%1$s接受了%4$s的邀请';
$Definition['%3$s approved %2$s membership application.'] = '%3$s批准%2$s的会员申请';
$Definition['%3$s created an account for %1$s.'] = '%3$s为%1$s创建一个帐户';
$Definition['%1$s updated %6$s profile.'] = '%1$s更新%6$s的个人资料';
$Definition['%1$s wrote on %4$s %5$s.'] = '%1$s记录道%4$s %5$s';
$Definition['%1$s changed %6$s profile picture.'] = '%1$s更改%6$s资料头像';
$Definition['%1$s changed %4$s permissions.'] = '%1$s更改%3$s的权限';
$Definition['%1$s commented on %4$s %8$s.'] = '%1$s对%3$s的%8$s添加评论';
$Definition['%1$s was added to the %2$s %3$s.'] = '%1$s被加入%2$s %3$s组';
$Definition['%1$s was removed from the %2$s %3$s.'] = '%1$s被%2$s %3$s组删除';
$Definition['%1$s was removed from the %2$s %3$s and added to the %4$s %5$s.'] = '%1$s从%2$s组转到%4$s组';
$Definition['You'] = '您';
$Definition['you'] = '您';
$Definition['your'] = '您的';
$Definition['he'] = '他';
$Definition['she'] = '她';
$Definition['his'] = '他的';
$Definition['her'] = '她的';
$Definition['somebody'] = '某人';
$Definition['wall'] = '墙';
$Definition['at'] = '@';
$Definition['dot'] = '.';
$Definition['Comment'] = '评论';
$Definition['Write a comment'] = '写评论';
$Definition['%1$s started a %8$s.'] = '%1$s发表%8$s';
$Definition['%1$s mentioned %3$s in a %8$s.'] = '%1$s在%8$s中提到%3$s';
$Definition['%1$s commented on your %8$s.'] = '%1$s对您的%8$s添加评论';
$Definition['%1$s sent you a %8$s.'] = '%1$s向您发送%8$s';
$Definition['message'] = '消息';
$Definition['discussion'] = '主题';
$Definition['bookmarked discussion'] = '标记的主题';
$Definition['comment'] = '评论';
$Definition['Not much happening here, yet.'] = '没有多少活动。';
$Definition['Welcome Aboard!'] = '欢迎加入!';


////////////////////////////////////
// General
$Definition['Discussions'] = '主题列表';
$Definition['Dashboard'] = '控制面板';
$Definition['Comments'] = '评论';
$Definition['%s comment'] = '%s条评论';
$Definition['%s comments'] = '%s条评论';
$Definition['%s new'] = '%s条新评论';
$Definition['Most recent by %1$s'] = '最新评论由%1$s添加';
$Definition['Announcement'] = '置顶';
$Definition['Announcements'] = '置顶主题';

$Definition['Inbox'] = '收件箱';
$Definition['New Conversation'] = '新邮件';
$Definition['Conversations'] = '对话';
$Definition['All Conversations'] = '所有邮件';
$Definition['%s message'] = '共%s个对话';
$Definition['%s messages'] = '共%s个对话';
$Definition['Start a New Conversation'] = '写新邮件';
$Definition['Delete Conversation'] = '删除邮件';
$Definition['Recipients'] = '收件人';
$Definition['Start Conversation'] = '发送';
$Definition['Clear Conversation History'] = '清除聊天历史';
$Definition['In this Conversation'] = '在本次对话中';
$Definition['%s and you'] = '%s和您';
$Definition['Add People to this Conversation'] = '添加联系人到本次对话';
$Definition['Add'] = '添加';
$Definition['You do not have any conversations.'] = '目前没有邮件';
$Definition['Add Message'] = '写消息';
$Definition['Send Message'] = '发送消息';
$Definition['Confirm'] = '确定';
$Definition['Are you sure you want to do that?'] = '确定要做此项操作?';
$Definition['Okay'] = '确定';
$Definition['Cancel'] = '取消';

$Definition['All Discussions'] = '所有主题';
$Definition['You have not started any discussions.'] = '您还没有发表过任何主题。';
$Definition['Start a New Discussion'] = '发表新主题';
$Definition['New Discussion'] = '新主题';
$Definition['My Discussions'] = '我的主题';

$Definition['Add Comment'] = '添加评论';
$Definition['Post Discussion'] = '发表主题';
$Definition['Post Comment'] = '发表评论';
$Definition['Save Draft'] = '存草稿';
$Definition['Preview'] = '预览';
$Definition['You have posted %1$s times within %2$s seconds. A spam block is now in effect on your account. You must wait at least %3$s seconds before attempting to post again.'] = '您在 %2$s 秒内已经发布了 %1$s 次内容。 垃圾信息屏闭功能已开启。 您必须等待 %3$s 秒以后才可以再次发言。';
$Definition['%1$s older comments'] = '%1$s前评论';
$Definition['%1$s more comments'] = '%1$s更多评论';
$Definition['Want to take part in this discussion? Click one of these:'] = '想要加入主题讨论? 请点击其中之一：';
$Definition['In this Discussion'] = '在本次主题讨论中';

$Definition['Announce'] = '置顶';
$Definition['Unannounce'] = '取消置顶';
$Definition['Sink'] = '下沉';
$Definition['Unsink'] = '解除下沉';
$Definition['Close'] = '锁定';
$Definition['Reopen'] = '取消锁定';
$Definition['Delete'] = '删除';
$Definition['Delete Discussion'] = '删除主题';
$Definition['Dismiss'] = '忽略置顶';
$Definition['Edit Comment'] = '编辑评论';

$Definition['Discussion Title'] = '标题';
$Definition['Edit Discussion'] = '编辑主题';
$Definition['Announce this discussion'] = '发布主题';
$Definition['Close this discussion'] = '锁定主题';
$Definition['Sink this discussion'] = '沉贴';

$Definition['Permalink'] = '永久链接';
$Definition['This discussion has been closed.'] = '主题已锁定';
$Definition['Back to Discussions'] = '返回主题列表';

$Definition['Howdy, Stranger!'] = '你好，游客!';
$Definition['No discussions were found.'] = '没有主题!';
$Definition['Sign Out'] = '退出';
$Definition['Hang on a sec while we sign you out.'] = '稍等，正在退出。';
$Definition['Category'] = '分类';
$Definition['Categories'] = '分类列表';

$Definition['My Drafts'] = '我的草稿';
$Definition['My Bookmarks'] = '我的关注';
$Definition['You do not have any drafts.'] = '没有草稿';
$Definition['Bookmarked Discussions'] = '关注的主题';
$Definition['You do not have any bookmarks.'] = '未添加关注';
$Definition['Bookmark'] = '添加关注';
$Definition['Unbookmark'] = '取消关注';


////////////////////////////////////
// Profile
$Definition['Notifications'] = '通知';
$Definition['Welcome to Vanilla!'] = '欢迎来到Vanilla!';
$Definition['Change My Picture'] = '更换头像';
$Definition['Change Picture'] = '更换图片';
$Definition['Select an image on your computer (2mb max)'] = '在计算机中选择图片 (最大2MB)';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = '上传文件时请确定您有权发布该图片, 并且不违反服务条款。';
$Definition['Edit My Thumbnail'] = '编辑缩略图';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = '在图像框下拖拽并调整图像大小来定义缩略图图标';
$Definition['Original'] = '原始图';
$Definition['Thumbnail'] = '缩略图';
$Definition['Save'] = '保存';
$Definition['Remove My Picture'] = '删除头像';
$Definition['Remove Picture'] = '删除图片';
$Definition['Your picture has been removed.'] = '头像已删除。';

$Definition['Edit My Account'] = '编辑我的帐户';
$Definition['Edit Account'] = '编辑帐户';
$Definition['Edit User'] = '编辑用户';
$Definition['Username'] = '用户名';
$Definition['Email'] = '电子邮件';
$Definition['Allow other members to see your email?'] = '允许其它用户看到您的电子邮件地址?';
$Definition['Email visible to other users'] = '电子邮件地址公开';
$Definition['Check all roles that apply to this user:'] = '查看此用户的所有权限:';
$Definition['Password Options'] = '密码选项';
$Definition['Reset Password'] = '重设密码';
$Definition['Reset password and send email notification to user'] = '重设密码并向用户发送提醒邮件';
$Definition['Gender'] = '性别';
$Definition['Male'] = '男';
$Definition['Female'] = '女';
$Definition['Change My Password'] = '更改我的密码';
$Definition['Old Password'] = '旧密码';
$Definition['New Password'] = '新密码';
$Definition['Confirm Password'] = '确认密码';
$Definition['Change Password'] = '更改密码';
$Definition['Your old password was incorrect.'] = '旧密码输入有误';
$Definition['Your password has been changed.'] = '密码已更改';

$Definition['My Invitations'] = '我的邀请';
$Definition['You have %s invitations left for this month.'] = '本月您有来自%s的邀请';
$Definition['Enter the email address of the person you would like to invite:'] = '输入受邀人的电子邮件地址';
$Definition['Invite'] = '邀请';
$Definition['Sent To'] = '发送给';
$Definition['On'] = '在';
$Definition['Status'] = '状态';
$Definition['Uninvite'] = '未邀请';
$Definition['Send Again'] = '再次发送';
$Definition['Pending'] = '待定';
$Definition['You cannot remove an invitation that has been accepted.'] = '已被接受的邀请不能删除';
$Definition['An invitation has already been sent to the email you entered.'] = '邀请已发送到您输入的邮件地址 ';
$Definition['The email you have entered is already related to an existing account.'] = '您输入的邮件地址已经绑定了一个帐号'; //doppelt - siehe oben
$Definition['You do not have enough invitations left.'] = '您没有足够的邀请';

$Definition['My Preferences'] = '个性化设置';
$Definition['Email Notifications'] = '电子邮件通知';
$Definition['Notify me when people write on my wall.'] = '当有人在我的主页留言时通知我';
$Definition['Notify me when people reply to my wall comments.'] = '当有人回复我的主题时通知我';
$Definition['Notify me of private messages.'] = '有私人消息时通知我';
$Definition['Notify me when I am added to private conversations.'] = '当我被加到私人聊天中时通知我';
$Definition['Notify me when people comment on my discussions.'] = '当有人对我的主题添加评论时通知我';
$Definition['Notify me when people mention me in discussion titles.'] = '当有人在主题中提到我时通知我';
$Definition['Notify me when people mention me in comments.'] = '当有人在评论中提到我时通知我';
$Definition['Notify me when people comment on my bookmarked discussions.'] = '当有人对我关注的主题添加评论时通知我';
$Definition['Save Preferences'] = '保存';
$Definition['Your preferences have been saved.'] = '个性化设置已保存';
$Definition['Your changes have been saved.'] = '更改已保存';
$Definition['Your changes have been saved successfully.'] = '更改保存成功'; // eines davon in github löschen
$Definition['Send %s a Message'] = '向%s发送消息';

$Definition['About'] = '关于';
$Definition['Name'] = '名字';
$Definition['Joined'] = '加入';
$Definition['Visits'] = '访问';
$Definition['Last Active'] = '上次在线';
$Definition['Roles'] = '身份';
$Definition['Write something about yourself...'] = '个人简介...';

$Definition['Password'] = '密码';
$Definition['Remember me on this computer'] = '本机记住登录状态';
$Definition['or'] = '或';
$Definition['Clear'] = '删除';
$Definition['Share'] = '发布';

$Definition['ValidateRegex '] = '格式不正确';
$Definition['ValidateRequired'] = '用户名不正确';
$Definition['ValidateRequiredArray'] = '数组验证';
$Definition['ValidateEmail'] = '电子邮箱不可用';
$Definition['ValidateDate'] = '日期验证';
$Definition['ValidateInteger'] = '整数验证';
$Definition['ValidateBoolean'] = '布尔验证';
$Definition['ValidateDecimal'] = '小数验证';
$Definition['ValidateTime'] = '时间验证';
$Definition['ValidateTimestamp'] = '时间标记验证';
$Definition['ValidateUsername '] = '用户名验证 用户名必须由3-20个字母，数字和下划线组成';
$Definition['ValidateLength'] = '长度不正确';
$Definition['ValidateEnum'] = '列举型验证';
$Definition['ValidateOneOrMoreArrayItemRequired'] = '验证一个或多个数组中的项';
$Definition['ValidateConnection '] = '连接验证 您指定的参数无法与数据库建立连接。 数据库返回如下错误： <code>%s</code>';
$Definition['ValidateMinimumAge'] = '最低年龄验证';
$Definition['ValidateMatch'] = '请确认密码';

$Definition['ErrorPermission'] = '权限错误';
$Definition['ErrorCredentials'] = '验证失败';
$Definition['ErrorPluginVersionMatch'] = '插件版本错误。可用插件{0} V1不符合版本要求({2})';
$Definition['ErrorPluginDisableRequired'] = '错误终止插件命令。插件{1}需要基于插件{0}运行，插件{0}不能终止';
$Definition['ErrorPluginEnableRequired'] = '错误调用插件命令。这个插件需要{ 0 }插件被打开后才可以使用';
$Definition['ErrorTermsOfService'] = '服务条款错误。您必须同意服务条款';
$Definition['ErrorRecordNotFound'] = '找不到记录错误。要求的记录找不到';

$Definition['PageDetailsMessageFull'] = '页面详情消息已满';
$Definition['PageDetailsMessage'] = '页面详情消息';
$Definition['RoleID'] = '身份编号';
$Definition['Garden.Registration.DefaultRoles'] = '花园。注册。默认身份';
$Definition['Garden.Title'] = '花园。标题';
$Definition['Garden.Email.SupportName'] = '花园。电子邮件。支持名字';
$Definition['Garden.Email.SupportAddress'] = '花园。电子邮件。支持地址';
$Definition['UrlCode'] = 'URL代码';
$Definition['OldPassword'] = '旧密码';

$Definition['RoleID'] = '身份编号';
$Definition['EmailInvitation'] = '你好!

    这是来自爱青大BBS的邀请信

	您的好友 %1$s 邀请你加入 %2$s. 欢迎点击下面的链接加入:

	  %3$s

	  祝你开心每一天!';
$Definition['EmailMembershipApproved'] = '你好： %1$s,

    这是来自爱青大BBS的通知信

	恭喜您，你的申请已被管理员通过，欢迎加入爱青大BBS. 点击下面的链接进行登录:

	  %2$s
	    
	  祝你开心每一天!';
$Definition['EmailNotification'] = '%1$s

	这是来自爱青大BBS的密码重置通知

	Follow the link below to check it out:
	%2$s

	祝你开心每一天!';
$Definition['EmailPassword'] = '你好 %1$s,

	这是来自爱青大BBS的密码重置通知

	%2$s 的密码已经被您重置 %3$s. 请用以下账号密码登录并修改您的密码:

	  Email: %6$s
	  Password: %5$s
	  Url: %4$s

	      祝你开心每一天!';
$Definition['EmailStoryNotification'] = '%1$s

	%3$s

	---
	Follow the link below to check it out:
	%2$s

	祝你开心每一天!';
$Definition['EmailWelcome'] = '你好 %1$s,

    这是来自爱青大BBS的欢迎信
    
	%2$s 已经为您创建了爱青大BBS的账户 %3$s. 请使用以下信息登录:

	  Email: %6$s
	  Password: %5$s
	  Url: %4$s

	      祝你开心每一天!';
$Definition['EmailWelcomeConnect'] = '你好 {User.Name},

	You have successfully connected to {Title}. Here is your information:

	  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.

祝你开心每一天!';
$Definition['EmailWelcomeRegister'] = '您好 {User.Name},

	恭喜您，成功注册了{Title} 账号. 以下是您的注册信息:

	  用户名: {User.Name}
      邮件: {User.Email}

访问地址 {/,url,domain}.

祝你开心每一天!';
$Definition['Use the content at this url as your homepage.'] = '默认首页，当用户访问 <strong>%s</strong>时，默认展现的页面，vanilla默认使用 "All Discussions" 页作为默认首页，你可以根据你的喜好来设置你的默认首页。';

$Definition['Category Management'] = '分类管理';

$Definition['All Categories'] = '所有分类';
$Definition['Categories &amp; Discussions'] = '分类 & 话题';
$Definition['Manage Plugins'] = '插件管理';
$Definition['PluginHelp'] = "vanilla提供了一个强大的插件系统，能够帮您增加一些有用的功能，例如增加投票，美化主题等等，vanilla默认有很多插件，如果你想好获得更多的插件，请点击这里 <a href=\"http://vanillaforums.org/addons\">获取插件</a> ，从官网获取";
$Definition['ApplicationHelp'] = "应用帮助。 您可以添加更多应用功能。<br />应用功能被加入到文件夹 %s,您可以在这里激活或关闭它"; 
$Definition['ThemeHelp'] = "和wordpress类似，vanilla也提供了强大的模板功能，你可以从官网下载模板文件，然后解压到 %s 文件夹，在后台你就能够看到模板选项，点击启用即可完成美化.";
$Definition['AddonProblems'] = "加载项问题<h2>Probleme?</h2><p>Läuft etwas schief mit einem Add-On? Wen dem so ist kannst du bestimmte Bereich deines Forums wahrscheinlich nicht nutzen. Deaktiviere sie manuell hier:</p>%s";
$Definition['Date.DefaultFormat'] = 'Y-m-d';
$Definition['Date.DefaultDayFormat'] = 'dd';
$Definition['Date.DefaultYearFormat'] = '%Y年%m月%d日';
$Definition['Date.DefaultTimeFormat'] = 'hh:mm:ss';
$Definition['Saved'] = '保存';

////////////////////////////////////
// Plugin Vanilla Replies
$Definition['Reply'] = '回复';
$Definition['Replies'] = '全部回复';
$Definition['Write a reply'] = '写回复';
$Definition['%s Reply'] = '回复';
$Definition['%s Replies'] = '全部回复';
$Definition['Show 1 more reply...'] = '再显示一条回复...';
$Definition['Show %s more replies...'] = '显示更多回复...';
$Definition['1$s replied to %4$s %8$s.'] = '%1$s回复%4$s %8$s.'; // bei Profile Activity; geht nicht


////////////////////////////////////
// Dashboard Menu
$Definition['← Visit Site'] = '← 访问网站';
$Definition['Site Settings'] = '网站设置';
$Definition['General'] = '全部';
$Definition['Routes'] = '路径';
$Definition['Messages'] = '消息';
$Definition['Import'] = '导入';
$Definition['Banner'] = '导航';
$Definition['Settings'] = '设置';
$Definition['Authentication'] = '认证';
$Definition['Homepage'] = '首页';
$Definition['Addons'] = '加载项';
$Definition['Applications'] = '应用';
$Definition['Plugins'] = '插件';
$Definition['Forum Settings'] = '论坛设置';
$Definition['Flood Control'] = '流量控制';
$Definition['Moderation'] = '审计';
$Definition['Themes'] = '主题';
$Definition['Locales'] = '国际化';
$Definition['Statistics'] = '统计';
$Definition['Roles & Permissions'] = '身份&权限';
$Definition['Registration'] = '注册';
$Definition['Advanced'] = '高级';
$Definition['Forum'] = '论坛设置';
$Definition['Edit/Delete Log'] = '编辑/删除 日志';

////////////////////////////////////
// Dashboard Buzz
$Definition["What's the Buzz?"] = '网站动态';
$Definition['Recently Active Users'] = '近期活跃的用户';
$Definition['Users'] = '用户';
$Definition['New users in the last day'] = '昨天注册的新用户';
$Definition['New users in the last week'] = '上周注册的新用户';
$Definition['New conversations in the last day'] = '昨天的新对话';
$Definition['New conversations in the last week'] = '上周的新对话';
$Definition['Conversation Messages'] = '对话消息';
$Definition['New messages in the last day'] = '昨天的新消息';
$Definition['New messages in the last week'] = '上周的新消息';
$Definition['New discussions in the last day'] = '昨天的新主题';
$Definition['New discussions in the last week'] = '上周的新主题';
$Definition['New comments in the last day'] = '昨天的新主题';
$Definition['New comments in the last week'] = '上周的新主题';

////////////////////////////////////
// Dashboard 外观
$Definition['Apply'] = '启用';
$Definition['Get More Themes'] = '从vanilla官方获取主题';
$Definition['Manage Themes'] = '主题管理';
$Definition['Current Theme'] = '正在使用的主题';
$Definition['Other Themes'] = '其他可用主题';
$Definition['All Pages'] = '所有页面（*）';
$Definition['All Forum Pages'] = '所有论坛讨论区页面';
$Definition['Enter the url to the page you would like to use as your homepage:'] = '输入你想要做为默认页（首页）的url地址：';
$Definition['Banner Title'] = '站点名';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = '站点名将显示在导航栏的最左边，如果用户上传了站点LOGO，那么将用LOGO代替';
$Definition['Banner Logo'] = '站点Logo';
$Definition['The banner logo appears at the top of your forum.'] = '站点LOGO将显示在论坛顶部';
$Definition['Messages can appear anywhere in your application.'] = '消息系统用来在应用的各个地方展示通知，可以用来向用户发布通知和新闻，例如重大更新，重大事件的发生等，在这里，你可以方便的管理你的消息';


////////////////////////////////////
// Dashboard 论坛设置
$Definition['Organize Categories'] = '分类管理';
$Definition['Manage Categories'] = '论坛分类管理';
$Definition['Add Category'] = '添加分类';
$Definition['Don\'t use Categories'] = '停用分类';
$Definition['Category Page Layout'] = '分类展示方式';
$Definition['Only Allow Each User To Post'] = '允许每个用户发布';
$Definition['Within'] = '在有限时间内';
$Definition['Or Spamblock For'] = '否则阻止发布';
$Definition['discussion(s)'] = '话题';
$Definition['comment(s)'] = '评论';
$Definition['seconds'] = '秒';
$Definition['minute(s)'] = '分钟';

////////////////////////////////////
// Dashboard Users

$Definition['Manage Users'] = '管理用户';
$Definition['Add User'] = '添加用户';
$Definition['%s user(s) found.'] = '共%s位用户';
$Definition['First Visit'] = '首次访问';
$Definition['Last Visit'] = '上次访问';
$Definition['Options'] = '选项';
$Definition['Edit'] = '编辑';
$Definition['Generate Password'] = '生成密码';
$Definition['Reveal Password'] = '显示密码';
$Definition['User Registration Settings'] = '用户注册设置';
$Definition['Method'] = '注册方式';
$Definition['Basic'] = '基础方式';
$Definition['Approval'] = '审核方式';
$Definition['Invitation'] = '邀请方式';
$Definition['New users fill out a simple form and are granted access immediately.'] = '新用户只需要填写一个简单的表单就立刻注册成功';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = '新用户需要提交申请，由管理员负责审核';
$Definition['Existing members send invitations to new members.'] = '老用户邀请新用户方式';
$Definition[' Require users to confirm their email addresses (recommended)']='需要用户确认邮件地址（推荐启用）';
$Definition['Key Type'] = 'Captcha 密钥类型';
$Definition['Key Value'] = 'Captcha 密钥值';
$Definition['Change the way that new users register with the site.'] = '选择新用户注册方式';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '
基础注册方式需要用户填写一个验证码来防止垃圾用户产生，你需要获取一个recaptcha.net的账户，注册这个账号是免费的，注册登录后获取一个Captcha私钥和密钥，
然后继续下面的设置。vanilla的验证码没有自己实现，而是通过调用recaptcha.net的开放接口实现的';
 
$Definition['Email Confirmation Role'] = '邮箱确认角色';
$Definition['Users will be assigned to this role until they\'ve confirmed their email addresses.'] = '新注册的用户将被设置为此角色，直到他们激活（收到确认信）';
////////////////////////////////////
// Dashboard Settings
$Definition['General Settings'] = '常规设置';
$Definition['Language'] = '语言';
$Definition['Application Title'] = '应用标题';
$Definition["Use Garden's .htaccess file to rewrite urls"] = '使用Garden\'s .htaccess 重写URL'; //--> geht nicht
$Definition['The server configuration for this setting could not be found. If you enable this setting your site may become unavailable.'] = '服务器的此项设置找不到。如果您仍使用此项设置，您的网站将不可用。'; //--> geht nicht
$Definition['Email sent from the application will be addressed from the following name and address'] = '应用程序将会按照以下的名字和地址发送电子邮件。';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = '我们将按默认设置使用本地邮件服务器。如果您想使用其它STMP 邮件服务器，请在下面设置。';
$Definition['Use an SMTP server to send email'] = '使用STMP服务器发送邮件'; //--> geht nicht

$Definition['Manage Routes'] = '管理路径';
$Definition['Add Route'] = '添加路径'; //--> geht nicht, ev. wegen URL
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = '路径会根据URL将用户转接到网站的不同端口'; //--> geht nicht, ev. wegen URL die noch folgt
$Definition['Route'] = '路径';
$Definition['Target'] = '目标';
$Definition['Type'] = '类型';
$Definition['Edit'] = '编辑'; //--> geht nicht, ev. wegen URL
$Definition['Route Expression'] = '路径展示';

$Definition['Manage Messages'] = '管理消息';
$Definition['Add Message'] = '写消息'; //--> geht nicht, ev. wegen URL
$Definition['Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.'] = '消息可以出现在应用程序中的任何位置。消息可以用来告诉用户新闻和事件。使用本页,通过拖放它们上升或下降来重组你的消息';
$Definition['Edit Message'] = '编辑消息';
$Definition['Location'] = '位置';
$Definition['Message'] = '消息';
$Definition['Disabled'] = '关闭'; //--> geht nicht, ev. wegen URL
$Definition['Delete'] = '删除'; //--> geht nicht, ev. wegen URL
$Definition['Page'] = '页';
$Definition['Every Page'] = '每页';
$Definition['Profile Page'] = '资料页';
$Definition['Discussions Page'] = '主题页';
$Definition['Comments Page'] = '评论页';
$Definition['Position'] = '位置';
$Definition['Above Main Content'] = '在主内容以上';
$Definition['Below Sidebar'] = '在工具条以下';
$Definition['Appearance'] = '外观';
$Definition['Information'] = '信息';
$Definition['Warning'] = '警告';
$Definition['Panel Box'] = '面板箱';
$Definition['None'] = '没有';
$Definition['Allow users to dismiss this message'] = '允许用户撤消该消息'; //--> geht nicht
$Definition['Enable this message'] = '激活消息'; //--> geht nicht

$Definition['Manage Applications'] = '管理应用';
$Definition['All'] = '全选';
$Definition['Enabled'] = '激活'; //--> geht nicht, ev. wegen URL
$Definition['Application'] = '应用';
$Definition['Description'] = '描述';
$Definition['Disable'] = '关闭';
$Definition['Version'] = '版本';
$Definition['By'] = '被';
$Definition['Visit Site'] = '访问网站';


////////////////////////////////////
// System & Error Messages
$Definition['A fatal error occurred while processing the request.<br />The server returned the following response: %s'] = '处理请求时发生致命错误。服务器返回如下内容: %s';
$Definition['The invitation was sent successfully.'] = '邀请发送成功';
$Definition['Your invitation has been sent.'] = '邀请已发送'; // evtl. raus
$Definition['The invitation was removed successfully.'] = '邀请已成功删除';
$Definition['Although the invitation was created successfully, the email failed to send. The server reported the following error: %s'] = '邀请创建成功，但邮件无法送达。服务器抛如下错误信息: %s';
$Definition['You must be authenticated in order to use this form.'] = '您必须经过验证才可以使用此表';


////////////////////////////////////
// System E-Mail
$Definition['[%s] Password Reset Request'] = '[%s]重设密码请求';
$Definition['[%s] Invitation'] = '[%s]邀请';
$Definition['[%s] Welcome Aboard!'] = '[%s]欢迎登录！';
$Definition['[%s] Password Reset'] = '[%s]重设密码';

/**
 * PLUGINS
 */
$Definition['Whos Online'] = '谁在线';
$Definition['Where should the plugin be shown?'] = '在哪里可以显示插件？';
$Definition['Whos Online'] = '谁在线';
$Definition['Who\'s Online Settings'] = '在线状态设置';
$Definition['Who\'s Online'] = '谁在线';
$Definition['Make me invisible? (Will not show you on the list)'] = '在线对其他用户不可见（你将不会出现在在线列表中）';
$Definition['%s said'] = '%s说到';
$Definition['Signature Settings'] = '签名设置';
$Definition['Quote'] = '引用';
$Definition['Whos Online'] = '在线用户';
$Definition['Voting'] = '投票';
$Definition['Tagging'] = '标签';
$Definition['Sections'] = '选项';
$Definition['Every'] = '所有页';
$Definition['Discussion'] = '只在话题页';
$Definition['Frequency'] = '频率';
$Definition['Rate of refresh'] = '间隔时间';
$Definition['In seconds'] = '秒';
$Definition['Top Posters'] = '英雄榜';


////////////////////////////////////
// Dashboard Gemeldete Inhalte
$Definition['Flagged Content'] = '标记内容';
$Definition['The following content has been flagged by users for moderator review.'] = '用户标记了以下内容给版主.';
$Definition['Enable Content Flagging'] = '标记开启';
$Definition['Content Flagging'] = '内容标记';


////////////////////////////////////
// New Definitions that need to be sorted
$Definition['Add a Comment'] = '添加评论';
$Definition['Write Comment'] = '写评论';
$Definition['Save Comment'] = '保存评论';
$Definition['Invited by'] = '邀请';
$Definition['Delete Account'] = '删除帐号';
$Definition['Edit Preferences'] = '编辑首选项';
$Definition['Started by %1$s'] = '由%1$s更新';
$Definition['Outgoing Email'] = '邮件';

$Definition['Max Comment Length'] = '评论字数上限';

$Definition['Discussions per Page'] = '每页主题';
$Definition['Comments per Page'] = '每页的评论';
$Definition['Refresh Comments'] = '刷新评论';
$Definition['Archive Discussions'] = '主题存档';


$Definition['Date.DefaultTimeFormat'] = '%H:%M';
$Definition['Date.DefaultDayFormat'] = '%b%e日';

//新增翻译项

$Definition['Tags'] = '标签';
$Definition['Register IP']='注册IP';
$Definition['Last IP']='最后登录IP';
$Definition['Notify me when people start new discussions.']='当有人发布新主题时通知我';
$Definition['Notify me when people comment on a discussion.']='当有人评论一个主题时通知我';
$Definition['Popup'] = '标签';

$Definition['Forgot?']='忘记密码';
$Definition['Keep me signed in']='记住登录状态';
$Definition['Security Check'] = '验证码';
$Definition['Enter your Email address or username'] = 'Email/用户名';
$Definition['Email/Username'] = 'Email/用户名';
$Definition["Don't have an account? %s"]='还没有账号？%s';
$Definition['Create One.']='立即注册';
$Definition["GuestModule.Message"]='貌似这位童鞋你是新来的吧？点下面的按钮加入我们!';
$Definition['%s New']='%s';
$Definition['%s New Plural']='%s';

$Definition['Popular'] = '最热门的';
$Definition['Vote'] = '投票';
$Definition['Views'] = '浏览';
$Definition['Popular Tags'] = '热门标签';
$Definition['Discussions'] = '主题列表';
$Definition['Activity'] = '动态';
$Definition['inbox'] = '收件箱';
$Definition['sorted by'] = '查看方式';
$Definition['Votes'] = '投票';
$Definition['Date Added'] = '发表时间';
$Definition['Unannounce'] = '取消置顶';
$Definition['Sink'] = '下沉';
$Definition['Delete Discussion'] = '删除主题';
$Definition['Tagged'] = '此主题使用的标签';
$Definition['Follow'] = '关注';
$Definition['Follows'] = '关注';
$Definition['Activity.Comment'] = '评论';

$Definition['Uploading...'] = '上传中...';
$Definition['Insert Image'] = '插入图片';
$Definition['Attach a file'] = '添加图片';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = '点击查看原始图片';
$Definition['Attachments'] = '附件';

$Definition['Redirecting...'] = '正在跳转...';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = '请稍候,如果没有跳转请<a href="%s">点击此处</a>手动跳转.';
$Definition['Add Info &amp; Create Account'] = '起个昵称吧';
$Definition['Choose a name to identify yourself on the site.'] = '输入您在论坛里显示的用户名';
$Definition['Connect'] = '确定';
$Definition['You must set a name!'] = '请输入用户名';
$Definition['This name is already used!'] = '此用户名已经存在';
$Definition['Sign in'] = '登录';
$Definition['I remember now!'] = '我想起来了!';

$Definition['This email is already used!'] = '此邮件已经使用';
$Definition['You do not have any notifications yet.'] = '目前没有通知';
$Definition['permalink'] = '传送门';
